services:

  # Local services are available on their ports, but also available on:
  # http://api.localhost.tiangolo.com: backend
  # http://dashboard.localhost.tiangolo.com: frontend
  # etc. To enable it, update .env, set:
  # DOMAIN=localhost.tiangolo.com
  sm-db:
    restart: "no"
    ports:
      - "5432:5432"

  sm-adminer:
    restart: "no"
    ports:
      - "8080:8080"

  sm-backend:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./backend
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    volumes:
      - ./backend/htmlcov:/app/htmlcov
    environment:
      SMTP_HOST: "sm-mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"

  sm-mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  sm-frontend:
    restart: "no"
    ports:
      - "5173:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development

  # sm-playwright:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.playwright
  #     args:
  #       - VITE_API_URL=http://sm-backend:8000
  #       - NODE_ENV=production
  #   ipc: host
  #   depends_on:
  #     - sm-backend
  #     - sm-mailcatcher
  #   env_file:
  #     - .env
  #   environment:
  #     - VITE_API_URL=http://sm-backend:8000
  #     - MAILCATCHER_HOST=http://sm-mailcatcher:1080
  #     - PLAYWRIGHT_HTML_HOST=0.0.0.0
  #     - CI=${CI}
  #   volumes:
  #     - ./frontend/blob-report:/app/blob-report
  #     - ./frontend/test-results:/app/test-results
  #   ports:
  #     - 9323:9323
