"""add_coreiot_token

Revision ID: 594d0d4c2ce0
Revises: f512f377f2df
Create Date: 2025-06-01 23:24:58.179908

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '594d0d4c2ce0'
down_revision = 'f512f377f2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coreiot_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'coreiot_access_token')
    # ### end Alembic commands ###