"""add_light

Revision ID: cb8b5d6f7593
Revises: 792bfb7c988a
Create Date: 2025-06-02 08:35:24.920983

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb8b5d6f7593'
down_revision = '792bfb7c988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreiotdata', sa.Column('light', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coreiotdata', 'light')
    # ### end Alembic commands ###