"""add coreiot data table

Revision ID: f512f377f2df
Revises: da8cfc6c54fb
Create Date: 2025-05-30 00:08:54.833977

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f512f377f2df'
down_revision = 'da8cfc6c54fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
